### ISSUE TITLE
Crash if json has no ObservationModelParameters attribute

### ISSUE THREAD

**Issue by dsato80** [hulop/blelocpp#13]
As I comment here
https://github.com/hulop/blelocpp/commit/1ff1de4684bff48dddf4cb2b5410a4d4762f31d7

It throws char string with error for shorthand. So please fix catch clause or the throwing object.

**Comment by muratams** [comment]
Fixed at commit 6406ef836d8bff3dede088caca8c08fae67bd8f4.
