### ISSUE TITLE
Building for android?

### ISSUE THREAD

**Issue by falcon03** [hulop/blelocpp#16]
I am working on a project that needs to incorporate indoor localization through the usage of iBeacons. I wanted to incorporate the blelocpp library to handle it, but the app should be available both on Android and on iOS. Is there any requirement that prevents this library from being built for Android?

**Comment by dsato80** [comment]
Hi @falcon03, our project has been focusing on iOS to support navigation for people with visual impairments but why we chose C++ to implement this library is for multi-platform support in the future (but no plan so far). So I believe it can be built for Android, but we have not tested well yet.
