### ISSUE TITLE
Bug in Observation Model based floor update

### ISSUE THREAD

**Issue by harsh-agarwal** [hulop/blelocpp#18]
Hi,

I was trying to understand the floor update using the observation model, and seems there is a potential bug in that section. 
The index used to iterate in both the for loops is the same. Would be glad if you could fix it and provide an explanation of how the floor transition algorithm is working :) 
```c++
// generate floors using weights and random numbers
            std::vector<int> floorsGenerated;
            for(int i = 0; i<states.size(); i++){
                double d = randomGenerator->nextDouble();
                double sumw = 0;
                int floorGen = std::numeric_limits<int>::max();
                for(int i=0; i<weights.size(); i++){
                    sumw+=weights.at(i);
                    if(d<=sumw){
                        floorGen = floors.at(i);
                        break;
                    }
                    if(i==weights.size()-1){
                        floorGen = floors.at(i);
                    }
                }
                assert(floorGen != std::numeric_limits<int>::max());
                floorsGenerated.push_back(floorGen);
            }
```

Thanks!

**Comment by muratams** [comment]
Not sure I follow. I don't see a bug in that section.
As for the basic concept of the floor transition, please consult the 5-th paragraph in Section IV-B of [our paper](https://ieeexplore.ieee.org/abstract/document/8444593).
The floor update function just generates sample numbers of the floor variable from a probability distribution proportional to the likelihood of the observation by using inverse transform sampling.

**Comment by harsh-agarwal** [comment]
I realized it's not a bug, it was making it look confusing. For the sake of readability, I changed the variables and created a request. Would be glad if you could merge :)
